### PR TITLE
chore: add web,nodejs, bundler targets

### PR DESCRIPTION
**Pull request by enthusiastmartin**
I am not really convinced that this is correct. 

Note that each target has its own package,json file. Perhaps there is way how to leverage that?

### CODE REVIEW

**Comment by jak-pan** [comment]
We could craft one package.json file in the root of the repo that will handle all three I guess?

**Comment by enthusiastmartin** [comment]
> 
> 
> We could craft one package.json file in the root of the repo that will handle all three I guess?

There is the package.json with main,browser and module section pointing to the corresponding js files. But not sure if it is correct and works ok.

**Comment by jak-pan** [comment]
> > We could craft one package.json file in the root of the repo that will handle all three I guess?
> 
> There is the package.json with main,browser and module section pointing to the corresponding js files. But not sure if it is correct and works ok.

We'll try. @smupyknight can you try to import this normally into HydraDX-js ?

**Comment by smupyknight** [comment]
@jak-pan it looks like node target works fine.
I was able to import it to HydraDX-js and then run the tests for wasm methods.
But some problem with web version when I am going to import HydraDX-js into HydraDX-app.

`error  in ./node_modules/hack-hydra-dx-wasm/build/web/hack_hydra_dx_wasm.js
Module parse failed: Unexpected token (195:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| async function init(input) {
|     if (typeof input === 'undefined') {
>         input = import.meta.url.replace(/\.js$/, '_bg.wasm');
|     }
|     const imports = {};
 @ ./node_modules/hydradx-js/lib/methods/query/index.js 161:69-98 180:98-127
 @ ./node_modules/hydradx-js/lib/api.js
 @ ./node_modules/hydradx-js/lib/index.js
 @ ./src/store/general/actions.ts
 @ ./src/store/general/index.ts
 @ ./src/store/index.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.137.61:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts`

**Comment by jak-pan** [comment]
> @jak-pan it looks like node target works fine.
> I was able to import it to HydraDX-js and then run the tests for wasm methods.
> But some problem with web version when I am going to import HydraDX-js into HydraDX-app.
> 
> ```
> error`  in ./node_modules/hack-hydra-dx-wasm/build/web/hack_hydra_dx_wasm.js
> Module parse failed: Unexpected token (195:22)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | async function init(input) {
> |     if (typeof input === 'undefined') {
> >         input = import.meta.url.replace(/\.js$/, '_bg.wasm');
> |     }
> |     const imports = {};
>  @ ./node_modules/hydradx-js/lib/methods/query/index.js 161:69-98 180:98-127
>  @ ./node_modules/hydradx-js/lib/api.js
>  @ ./node_modules/hydradx-js/lib/index.js
>  @ ./src/store/general/actions.ts
>  @ ./src/store/general/index.ts
>  @ ./src/store/index.ts
>  @ ./src/main.ts
>  @ multi (webpack)-dev-server/client?http://192.168.137.61:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
> ```
> 
> image

This is probably because HydraDX-js itself should be a package that has different targets for different platforms. Not sure if it can do this automatically. Needs a little bit of digging.

**Pull request merged**
