### PR TITLE
Wasm repo importable

### PR DESCRIPTION
**Pull request by smupyknight**

### CODE REVIEW

**Review by enthusiastmartin — DISMISSED** [review]
Right. that's why it probably did not work for @jak-pan  at the very beginining when he was not able to import for some reason. 

Anyway -just for info -  this is going to be refactored soon and among other changes -  it will be also renamed ( the hack_ prefix will be removed ).

**Comment by enthusiastmartin** [comment]
well, actually. this is all generated when i run wasm build. 

 So now, when i make changes and rerun - it will be back to the original implementation.
 
 Any specific reason why it has to be done in this way ? ( i mean, changes to the js files ).

**Comment by jak-pan** [comment]
Actually it was not this issue. It was much dumber. I tried to import wasm in nodejs like you do it in javascript.

**Comment by jak-pan** [comment]
But yes. We should probably remove the demo part and generate correctly. I'm not sure too why we need the changes in js as it should work in webpack like presented. Just needs a config I guess.

**Comment by jak-pan** [comment]
the #2 is the culprit.

**Pull request closed without merging**
